### ISSUE TITLE
Why is the `k` letter small?

### ISSUE THREAD

**Issue by tebaly** [cerberus-ab/human-readable-numbers#6]
https://github.com/cerberus-ab/human-readable-numbers/blob/cb24b3aa5ade3fa4f4205ed6a3c50ff4743f47ee/src/index.js#L12

After all, the rest are in upper case.

**Comment by cerberus-ab** [comment]
Because it's based on [SI prefixes](https://physics.nist.gov/cuu/Units/prefixes.html) where 'k' is in lower case.

**Comment by tebaly** [comment]
Ok... I'll just add `text-transform: uppercase;` :)
